apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: banking-etl-daily
  namespace: banking-etl
spec:
  schedule: "0 2 * * *"
  timezone: UTC
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  workflowSpec:
    workflowTemplateRef:
      name: banking-etl
