-- gold.dim_branch: port of DWH.dbo.DimBranch (sql_scripts/01_create_tables.sql).
-- Loaded by ticket 5 (Load_DimBranch) as SCD-1 via banking_etl.gold.merge.merge_scd1.
-- Placeholders are substituted by banking_etl.gold.ddl from banking_etl.config.Settings.
-- Blocks between /*uc:begin*/ and /*uc:end*/ are Unity Catalog-only and are stripped for OSS Delta.
CREATE TABLE IF NOT EXISTS ${dim_branch} (
  BranchKey BIGINT GENERATED BY DEFAULT AS IDENTITY COMMENT 'Surrogate key (identity). Stable across SCD-1 merges; never written by loads.',
  BranchID INT NOT NULL COMMENT 'Natural key from Sample_DB.dbo.branch.branch_id (legacy PRIMARY KEY of DimBranch).',
  BranchName STRING COMMENT 'Branch name (legacy VARCHAR(100)).',
  BranchLocation STRING COMMENT 'Branch street address (legacy VARCHAR(255)).'
  /*uc:begin*/, CONSTRAINT pk_dim_branch PRIMARY KEY (BranchID)/*uc:end*/
)
USING DELTA
COMMENT 'Branch dimension (SCD-1). Port of DWH.dbo.DimBranch; legacy PascalCase columns kept for reconciliation parity.'
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true'
);
