-- gold.dim_account: port of DWH.dbo.DimAccount (sql_scripts/01_create_tables.sql).
-- Loaded by ticket 6 (Load_DimAccount) as SCD-1 via banking_etl.gold.merge.merge_scd1.
-- Placeholders are substituted by banking_etl.gold.ddl from banking_etl.config.Settings.
-- Blocks between /*uc:begin*/ and /*uc:end*/ are Unity Catalog-only and are stripped for OSS Delta.
CREATE TABLE IF NOT EXISTS ${dim_account} (
  AccountKey BIGINT GENERATED BY DEFAULT AS IDENTITY COMMENT 'Surrogate key (identity). Stable across SCD-1 merges; never written by loads.',
  AccountID INT NOT NULL COMMENT 'Natural key from Sample_DB.dbo.account.account_id (legacy PRIMARY KEY of DimAccount).',
  CustomerID INT COMMENT 'Owning customer natural key (no FK in the legacy DDL, none added here).',
  AccountType STRING COMMENT 'Account type, e.g. SAVING / CHECKING (legacy VARCHAR(50)).',
  Balance DECIMAL(19,4) COMMENT 'Account balance (legacy MONEY -> DECIMAL(19,4)).',
  DateOpened DATE COMMENT 'Date the account was opened (legacy DATE; source DATETIME truncated to date).',
  Status STRING COMMENT 'Account status, e.g. ACTIVE / TERMINATED (legacy VARCHAR(50)).'
  /*uc:begin*/, CONSTRAINT pk_dim_account PRIMARY KEY (AccountID)/*uc:end*/
)
USING DELTA
COMMENT 'Account dimension (SCD-1). Port of DWH.dbo.DimAccount; legacy PascalCase columns kept for reconciliation parity.'
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true'
);
