-- gold.dim_customer: port of DWH.dbo.DimCustomer (customer x city x state, sql_scripts/01_create_tables.sql).
-- Loaded by ticket 7 (Load_DimCustomer) as SCD-1 via banking_etl.gold.merge.merge_scd1.
-- Placeholders are substituted by banking_etl.gold.ddl from banking_etl.config.Settings.
-- Blocks between /*uc:begin*/ and /*uc:end*/ are Unity Catalog-only and are stripped for OSS Delta.
CREATE TABLE IF NOT EXISTS ${dim_customer} (
  CustomerKey BIGINT GENERATED BY DEFAULT AS IDENTITY COMMENT 'Surrogate key (identity). Stable across SCD-1 merges; never written by loads.',
  CustomerID INT NOT NULL COMMENT 'Natural key from Sample_DB.dbo.customer.customer_id (legacy PRIMARY KEY of DimCustomer).',
  CustomerName STRING COMMENT 'Customer name, uppercased by the Talend tMap (legacy VARCHAR(100)).',
  Address STRING COMMENT 'Street address (legacy VARCHAR(255)).',
  CityName STRING COMMENT 'City name from Sample_DB.dbo.city (legacy VARCHAR(100)).',
  StateName STRING COMMENT 'State name from Sample_DB.dbo.state (legacy VARCHAR(100)).',
  Age INT COMMENT 'Customer age in years (source varchar(3) cast to INT).',
  Gender STRING COMMENT 'Gender (legacy VARCHAR(10)).',
  Email STRING COMMENT 'E-mail address (legacy VARCHAR(100)).'
  /*uc:begin*/, CONSTRAINT pk_dim_customer PRIMARY KEY (CustomerID)/*uc:end*/
)
USING DELTA
COMMENT 'Customer dimension (SCD-1), denormalised customer x city x state. Port of DWH.dbo.DimCustomer; legacy PascalCase columns kept for reconciliation parity.'
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true'
);

-- Enforced by Delta on every write (drop + add keeps re-runs idempotent).
ALTER TABLE ${dim_customer} DROP CONSTRAINT IF EXISTS ck_dim_customer_age;
ALTER TABLE ${dim_customer} ADD CONSTRAINT ck_dim_customer_age CHECK (Age IS NULL OR Age BETWEEN 0 AND 150);
