"""Idempotent Unity Catalog setup for the banking ETL lakehouse.

Creates ``<catalog>.<prefix>{bronze,silver,gold,ops}``, the landing volume
``<catalog>.<prefix>bronze.landing`` (plus its standard folders) and read
grants for ``account users``. Every statement is safe to re-run.

Backends:
  * SQL warehouse (statement-execution API) -- run from a laptop/CI::

        python databricks/setup/setup_unity_catalog.py --catalog migration_demo \
            --schema-prefix banking_mig_ [--warehouse-id ID] [--dry-run]

  * Spark session -- used by ``setup_unity_catalog_notebook.py`` (job/bundle)
    and, with ``unity_catalog=False``, by local pytest.

``--print-sql`` renders the statements; ``unity_catalog_setup.sql`` is that
output for the default dev environment.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from dataclasses import dataclass
from typing import Callable, Iterable, List, Optional, Sequence

_HERE = os.path.dirname(os.path.abspath(__file__))
_SRC = os.path.join(os.path.dirname(_HERE), "src")
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)

from banking_etl.common.config import (  # noqa: E402
    BRONZE,
    LANDING_SUBDIRS,
    LAYER_COMMENTS,
    EnvConfig,
    quote_identifier as q,
)

SCHEMA_PRIVILEGES = ("USE SCHEMA", "SELECT", "EXECUTE")
VOLUME_PRIVILEGES = ("READ VOLUME",)
LANDING_COMMENT = (
    "Landing zone for raw source extracts: transactions/{csv,excel}/ and sample_db/<table>/."
)

Executor = Callable[[str], List[tuple]]


@dataclass(frozen=True)
class Statement:
    sql: str
    kind: str
    # Optional statements may fail with PERMISSION_DENIED (e.g. the service
    # principal does not own the catalog) without failing the setup.
    optional: bool = False


def _lit(text: str) -> str:
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _schema_ref(cfg: EnvConfig, layer: str, unity_catalog: bool) -> str:
    schema = q(cfg.schema_name(layer))
    return f"{q(cfg.catalog)}.{schema}" if unity_catalog else schema


def build_statements(cfg: EnvConfig, unity_catalog: bool = True) -> List[Statement]:
    principal = q(cfg.grant_principal)
    stmts: List[Statement] = []
    if unity_catalog:
        stmts.append(
            Statement(f"GRANT USE CATALOG ON CATALOG {q(cfg.catalog)} TO {principal}", "grant", optional=True)
        )
    for layer in cfg.layers:
        ref = _schema_ref(cfg, layer, unity_catalog)
        comment = _lit(LAYER_COMMENTS.get(layer, f"{layer} layer of the banking ETL lakehouse."))
        stmts.append(Statement(f"CREATE SCHEMA IF NOT EXISTS {ref} COMMENT {comment}", "schema"))
        stmts.append(Statement(f"COMMENT ON SCHEMA {ref} IS {comment}", "comment"))
    if unity_catalog:
        volume = f"{_schema_ref(cfg, BRONZE, True)}.{q(cfg.landing_volume)}"
        stmts.append(
            Statement(f"CREATE VOLUME IF NOT EXISTS {volume} COMMENT {_lit(LANDING_COMMENT)}", "volume")
        )
        for layer in cfg.layers:
            ref = _schema_ref(cfg, layer, True)
            stmts.append(
                Statement(f"GRANT {', '.join(SCHEMA_PRIVILEGES)} ON SCHEMA {ref} TO {principal}", "grant")
            )
        stmts.append(Statement(f"GRANT {', '.join(VOLUME_PRIVILEGES)} ON VOLUME {volume} TO {principal}", "grant"))
    return stmts


def render_sql(cfg: EnvConfig, unity_catalog: bool = True) -> str:
    header = [
        "-- Generated by databricks/setup/setup_unity_catalog.py --print-sql; do not edit by hand.",
        f"-- Environment: catalog={cfg.catalog} schema_prefix={cfg.schema_prefix} "
        f"landing_volume={cfg.landing_volume} grant_principal={cfg.grant_principal}",
        "-- Idempotent: safe to re-run. Statements marked OPTIONAL need catalog ownership/MANAGE and",
        "-- are skipped by the Python runner when they fail with PERMISSION_DENIED.",
        "",
    ]
    body = []
    for s in build_statements(cfg, unity_catalog):
        if s.optional:
            body.append("-- OPTIONAL")
        body.append(s.sql + ";")
    return "\n".join(header + body) + "\n"


def _is_permission_error(exc: BaseException) -> bool:
    text = str(exc).upper()
    return any(t in text for t in ("PERMISSION_DENIED", "DOES NOT HAVE", "INSUFFICIENT_PERMISSIONS"))


def apply_statements(statements: Iterable[Statement], execute: Executor) -> List[dict]:
    results = []
    for s in statements:
        try:
            execute(s.sql)
            results.append({"kind": s.kind, "sql": s.sql, "status": "ok"})
        except Exception as exc:  # noqa: BLE001 - re-raised unless optional
            if s.optional and _is_permission_error(exc):
                results.append({"kind": s.kind, "sql": s.sql, "status": "skipped", "reason": str(exc)[:300]})
            else:
                raise
    return results


def landing_dirs(cfg: EnvConfig, base: Optional[str] = None) -> List[str]:
    root = base if base is not None else cfg.landing_path
    return [f"{root.rstrip('/')}/{sub}" for sub in LANDING_SUBDIRS]


# --------------------------------------------------------------------------- #
# Spark backend (notebook / local tests)
# --------------------------------------------------------------------------- #


def spark_executor(spark) -> Executor:
    return lambda sql: [tuple(r) for r in spark.sql(sql).collect()]


def setup_with_spark(
    spark,
    cfg: EnvConfig,
    unity_catalog: bool = True,
    mkdirs: Optional[Callable[[str], object]] = None,
    landing_base: Optional[str] = None,
) -> dict:
    """Apply the setup through a Spark session and return a JSON-able report.

    ``unity_catalog=False`` targets the default (Hive/session) catalog of a
    local Spark session: schemas only, no volume or grants.
    """
    results = apply_statements(build_statements(cfg, unity_catalog), spark_executor(spark))
    dirs = []
    if mkdirs is not None:
        for d in landing_dirs(cfg, landing_base):
            if mkdirs(d) is False:
                raise RuntimeError(f"Failed to create landing directory: {d}")
            dirs.append(d)
    if unity_catalog:
        rows = spark.sql(f"SHOW SCHEMAS IN {q(cfg.catalog)} LIKE '{cfg.schema_prefix}*'").collect()
    else:
        rows = spark.sql(f"SHOW SCHEMAS LIKE '{cfg.schema_prefix}*'").collect()
    return {
        "config": cfg.__dict__ | {"layers": list(cfg.layers)},
        "statements": results,
        "landing_dirs": dirs,
        "schemas": sorted(r[0] for r in rows),
    }


# --------------------------------------------------------------------------- #
# SQL warehouse backend (statement-execution API)
# --------------------------------------------------------------------------- #


def warehouse_executor(client, warehouse_id: str, timeout_s: int = 600) -> Executor:
    from databricks.sdk.service.sql import StatementState

    terminal = {StatementState.SUCCEEDED, StatementState.FAILED, StatementState.CANCELED, StatementState.CLOSED}

    def run(sql: str) -> List[tuple]:
        resp = client.statement_execution.execute_statement(
            statement=sql, warehouse_id=warehouse_id, wait_timeout="50s"
        )
        deadline = time.time() + timeout_s
        while resp.status.state not in terminal:
            if time.time() > deadline:
                raise TimeoutError(f"Statement {resp.statement_id} timed out: {sql}")
            time.sleep(3)
            resp = client.statement_execution.get_statement(resp.statement_id)
        if resp.status.state != StatementState.SUCCEEDED:
            err = resp.status.error
            raise RuntimeError(f"{err.error_code if err else ''}: {err.message if err else resp.status.state}")
        data = resp.result.data_array if resp.result and resp.result.data_array else []
        return [tuple(row) for row in data]

    return run


def pick_warehouse(client) -> str:
    env_id = os.environ.get("DATABRICKS_WAREHOUSE_ID")
    if env_id:
        return env_id
    warehouses = list(client.warehouses.list())
    if not warehouses:
        raise RuntimeError("No SQL warehouse available; pass --warehouse-id")
    return warehouses[0].id


def setup_with_warehouse(client, warehouse_id: str, cfg: EnvConfig) -> dict:
    execute = warehouse_executor(client, warehouse_id)
    results = apply_statements(build_statements(cfg, True), execute)
    dirs = []
    for d in landing_dirs(cfg):
        client.files.create_directory(d)
        dirs.append(d)
    schemas = execute(f"SHOW SCHEMAS IN {q(cfg.catalog)} LIKE '{cfg.schema_prefix}*'")
    volume = execute(f"DESCRIBE VOLUME {q(cfg.catalog)}.{q(cfg.schema_name(BRONZE))}.{q(cfg.landing_volume)}")
    return {
        "config": cfg.__dict__ | {"layers": list(cfg.layers)},
        "warehouse_id": warehouse_id,
        "statements": results,
        "landing_dirs": dirs,
        "schemas": sorted(r[0] for r in schemas),
        "volume": [list(r) for r in volume],
    }


def _parse_args(argv: Optional[Sequence[str]]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--catalog")
    p.add_argument("--schema-prefix")
    p.add_argument("--landing-volume")
    p.add_argument("--grant-principal")
    p.add_argument("--warehouse-id")
    p.add_argument("--print-sql", action="store_true", help="print the rendered SQL and exit")
    p.add_argument("--dry-run", action="store_true", help="alias of --print-sql")
    return p.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _parse_args(argv)
    cfg = EnvConfig.from_env(
        catalog=args.catalog,
        schema_prefix=args.schema_prefix,
        landing_volume=args.landing_volume,
        grant_principal=args.grant_principal,
    )
    if args.print_sql or args.dry_run:
        sys.stdout.write(render_sql(cfg))
        return 0
    from databricks.sdk import WorkspaceClient

    client = WorkspaceClient()
    report = setup_with_warehouse(client, args.warehouse_id or pick_warehouse(client), cfg)
    print(json.dumps(report, indent=2, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
