-- Generated by databricks/setup/setup_unity_catalog.py --print-sql; do not edit by hand.
-- Environment: catalog=migration_demo schema_prefix=banking_mig_ landing_volume=landing grant_principal=account users
-- Idempotent: safe to re-run. Statements marked OPTIONAL need catalog ownership/MANAGE and
-- are skipped by the Python runner when they fail with PERMISSION_DENIED.

-- OPTIONAL
GRANT USE CATALOG ON CATALOG `migration_demo` TO `account users`;
CREATE SCHEMA IF NOT EXISTS `migration_demo`.`banking_mig_bronze` COMMENT 'Bronze: raw, append-only copies of the SQL Server `sample` DB and the transaction Excel/CSV files.';
COMMENT ON SCHEMA `migration_demo`.`banking_mig_bronze` IS 'Bronze: raw, append-only copies of the SQL Server `sample` DB and the transaction Excel/CSV files.';
CREATE SCHEMA IF NOT EXISTS `migration_demo`.`banking_mig_silver` COMMENT 'Silver: cleansed, typed and deduplicated entities (branch, account, customer, transaction).';
COMMENT ON SCHEMA `migration_demo`.`banking_mig_silver` IS 'Silver: cleansed, typed and deduplicated entities (branch, account, customer, transaction).';
CREATE SCHEMA IF NOT EXISTS `migration_demo`.`banking_mig_gold` COMMENT 'Gold: star schema replacing the legacy DWH (dim_branch, dim_account, dim_customer, fact_transaction) and analytics functions.';
COMMENT ON SCHEMA `migration_demo`.`banking_mig_gold` IS 'Gold: star schema replacing the legacy DWH (dim_branch, dim_account, dim_customer, fact_transaction) and analytics functions.';
CREATE SCHEMA IF NOT EXISTS `migration_demo`.`banking_mig_ops` COMMENT 'Ops: run audit, reject and data-quality tables for the banking ETL migration.';
COMMENT ON SCHEMA `migration_demo`.`banking_mig_ops` IS 'Ops: run audit, reject and data-quality tables for the banking ETL migration.';
CREATE VOLUME IF NOT EXISTS `migration_demo`.`banking_mig_bronze`.`landing` COMMENT 'Landing zone for raw source extracts: transactions/{csv,excel}/ and sample_db/<table>/.';
GRANT USE SCHEMA, SELECT, EXECUTE ON SCHEMA `migration_demo`.`banking_mig_bronze` TO `account users`;
GRANT USE SCHEMA, SELECT, EXECUTE ON SCHEMA `migration_demo`.`banking_mig_silver` TO `account users`;
GRANT USE SCHEMA, SELECT, EXECUTE ON SCHEMA `migration_demo`.`banking_mig_gold` TO `account users`;
GRANT USE SCHEMA, SELECT, EXECUTE ON SCHEMA `migration_demo`.`banking_mig_ops` TO `account users`;
GRANT READ VOLUME ON VOLUME `migration_demo`.`banking_mig_bronze`.`landing` TO `account users`;
