# Databricks notebook source
# MAGIC %md
# MAGIC # silver.account -> gold.dim_account (ticket 6, Talend `Load_DimAccount`)
# MAGIC SCD-1 `MERGE` on `AccountID` via `banking_etl.gold.merge.merge_scd1`: updates changed attributes,
# MAGIC inserts new accounts, never deletes; `AccountKey` (identity) is generated by Delta and stays stable.
# MAGIC Creates the gold star schema first if `dim_account` is missing (Talend `CREATE_IF_NOT_EXISTS`).
# MAGIC
# MAGIC Widgets: `catalog`, `schema_prefix`. Logic: `src/banking_etl/dims/account.py`.

# COMMAND ----------

import json
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..", "..", "src")))

from banking_etl.config import settings_from_widgets
from banking_etl.dims.account import load_dim_account

settings = settings_from_widgets(dbutils)  # noqa: F821 - provided by Databricks
print(settings)

# COMMAND ----------

result = load_dim_account(spark, settings)  # noqa: F821
print(json.dumps(result, indent=2))

# COMMAND ----------

dbutils.notebook.exit(json.dumps(result))  # noqa: F821
