-- GENERATED by `python -m banking_etl.gold.ddl --write-sql databricks/sql/ddl`; do not edit by hand.
-- Source of truth: databricks/src/banking_etl/gold/ddl.py (port of sql_scripts/01_create_tables.sql).
-- Type mapping: docs/type_mapping.md. Re-running ADD CONSTRAINT on an existing table fails;
-- use banking_etl.gold.ddl.apply_star_schema for an idempotent apply.

CREATE SCHEMA IF NOT EXISTS migration_demo.banking_mig_silver COMMENT 'Silver: cleansed, typed and deduplicated entities (branch, account, customer, transaction).';

CREATE SCHEMA IF NOT EXISTS migration_demo.banking_mig_gold COMMENT 'Gold: star schema replacing the legacy DWH (dim_branch, dim_account, dim_customer, fact_transaction) and analytics functions.';
