-- GENERATED by `python -m banking_etl.gold.ddl --write-sql databricks/sql/ddl`; do not edit by hand.
-- Source of truth: databricks/src/banking_etl/gold/ddl.py (port of sql_scripts/01_create_tables.sql).
-- Type mapping: docs/type_mapping.md. Re-running ADD CONSTRAINT on an existing table fails;
-- use banking_etl.gold.ddl.apply_star_schema for an idempotent apply.

CREATE TABLE IF NOT EXISTS migration_demo.banking_mig_silver.branch (
  branch_id INT NOT NULL COMMENT 'Branch natural key (primary key). Legacy: BranchID INT.',
  branch_name STRING COMMENT 'Branch name. Max length 100 (CHECK). Legacy: BranchName VARCHAR(100).',
  branch_location STRING COMMENT 'Branch location. Max length 255 (CHECK). Legacy: BranchLocation VARCHAR(255).',
  _source_system STRING NOT NULL COMMENT 'Source stream the row came from: sqlserver, excel or csv (transactions); sqlserver for master data.',
  _ingested_at TIMESTAMP COMMENT 'Timestamp the row was written to silver.',
  CONSTRAINT pk_branch PRIMARY KEY (branch_id) NOT ENFORCED
)
USING DELTA
COMMENT 'Silver conformed branch entity from sample.dbo.branch; source of gold.dim_branch.'
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true'
);

ALTER TABLE migration_demo.banking_mig_silver.branch ADD CONSTRAINT ck_branch_branch_name_len CHECK (branch_name IS NULL OR length(branch_name) <= 100);

ALTER TABLE migration_demo.banking_mig_silver.branch ADD CONSTRAINT ck_branch_branch_location_len CHECK (branch_location IS NULL OR length(branch_location) <= 255);

CREATE TABLE IF NOT EXISTS migration_demo.banking_mig_silver.account (
  account_id INT NOT NULL COMMENT 'Account natural key (primary key). Legacy: AccountID INT.',
  customer_id INT COMMENT 'Owning customer (joins dim_customer.customer_id). Legacy: CustomerID INT.',
  account_type STRING COMMENT 'Account product type. Max length 50 (CHECK). Legacy: AccountType VARCHAR(50).',
  balance DECIMAL(19,4) COMMENT 'Account balance. Legacy: Balance MONEY.',
  date_opened DATE COMMENT 'Date the account was opened. Legacy: DateOpened DATE.',
  status STRING COMMENT 'Account status; sp_BalancePerCustomer filters status = \'active\'. Max length 50 (CHECK). Legacy: Status VARCHAR(50).',
  _source_system STRING NOT NULL COMMENT 'Source stream the row came from: sqlserver, excel or csv (transactions); sqlserver for master data.',
  _ingested_at TIMESTAMP COMMENT 'Timestamp the row was written to silver.',
  CONSTRAINT pk_account PRIMARY KEY (account_id) NOT ENFORCED
)
USING DELTA
COMMENT 'Silver conformed account entity from sample.dbo.account; source of gold.dim_account.'
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true'
);

ALTER TABLE migration_demo.banking_mig_silver.account ADD CONSTRAINT ck_account_account_type_len CHECK (account_type IS NULL OR length(account_type) <= 50);

ALTER TABLE migration_demo.banking_mig_silver.account ADD CONSTRAINT ck_account_status_len CHECK (status IS NULL OR length(status) <= 50);

CREATE TABLE IF NOT EXISTS migration_demo.banking_mig_silver.customer (
  customer_id INT NOT NULL COMMENT 'Customer natural key (primary key). Legacy: CustomerID INT.',
  customer_name STRING COMMENT 'Customer name (upper-cased by Load_DimCustomer tMap). Max length 100 (CHECK). Legacy: CustomerName VARCHAR(100).',
  address STRING COMMENT 'Street address (upper-cased by Load_DimCustomer tMap). Max length 255 (CHECK). Legacy: Address VARCHAR(255).',
  city_name STRING COMMENT 'City name, denormalised from source city (upper-cased). Max length 100 (CHECK). Legacy: CityName VARCHAR(100).',
  state_name STRING COMMENT 'State name, denormalised from source state (upper-cased). Max length 100 (CHECK). Legacy: StateName VARCHAR(100).',
  age INT COMMENT 'Customer age in years. Legacy: Age INT.',
  gender STRING COMMENT 'Customer gender (upper-cased by Load_DimCustomer tMap). Max length 10 (CHECK). Legacy: Gender VARCHAR(10).',
  email STRING COMMENT 'Customer e-mail address. Max length 100 (CHECK). Legacy: Email VARCHAR(100).',
  _source_system STRING NOT NULL COMMENT 'Source stream the row came from: sqlserver, excel or csv (transactions); sqlserver for master data.',
  _ingested_at TIMESTAMP COMMENT 'Timestamp the row was written to silver.',
  CONSTRAINT pk_customer PRIMARY KEY (customer_id) NOT ENFORCED
)
USING DELTA
COMMENT 'Silver conformed customer entity (customer joined to city and state); source of gold.dim_customer.'
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true'
);

ALTER TABLE migration_demo.banking_mig_silver.customer ADD CONSTRAINT ck_customer_customer_name_len CHECK (customer_name IS NULL OR length(customer_name) <= 100);

ALTER TABLE migration_demo.banking_mig_silver.customer ADD CONSTRAINT ck_customer_address_len CHECK (address IS NULL OR length(address) <= 255);

ALTER TABLE migration_demo.banking_mig_silver.customer ADD CONSTRAINT ck_customer_city_name_len CHECK (city_name IS NULL OR length(city_name) <= 100);

ALTER TABLE migration_demo.banking_mig_silver.customer ADD CONSTRAINT ck_customer_state_name_len CHECK (state_name IS NULL OR length(state_name) <= 100);

ALTER TABLE migration_demo.banking_mig_silver.customer ADD CONSTRAINT ck_customer_gender_len CHECK (gender IS NULL OR length(gender) <= 10);

ALTER TABLE migration_demo.banking_mig_silver.customer ADD CONSTRAINT ck_customer_email_len CHECK (email IS NULL OR length(email) <= 100);

CREATE TABLE IF NOT EXISTS migration_demo.banking_mig_silver.transaction (
  transaction_id INT NOT NULL COMMENT 'Transaction natural key (primary key; unique after tUniqRow dedup). Legacy: TransactionID INT.',
  account_id INT COMMENT 'Account of the transaction (FK to dim_account.account_id). Legacy: AccountID INT.',
  transaction_date TIMESTAMP COMMENT 'Transaction timestamp (session time zone UTC; microsecond precision vs DATETIME 3.33 ms). Legacy: TransactionDate DATETIME.',
  amount DECIMAL(19,4) COMMENT 'Transaction amount (unsigned; sign is derived from transaction_type). Legacy: Amount MONEY.',
  transaction_type STRING COMMENT 'Transaction type; \'Deposit\' adds, anything else subtracts in sp_BalancePerCustomer. Max length 50 (CHECK). Legacy: TransactionType VARCHAR(50).',
  branch_id INT COMMENT 'Branch of the transaction (FK to dim_branch.branch_id). Legacy: BranchID INT.',
  _source_system STRING NOT NULL COMMENT 'Source stream the row came from: sqlserver, excel or csv (transactions); sqlserver for master data.',
  _ingested_at TIMESTAMP COMMENT 'Timestamp the row was written to silver.',
  CONSTRAINT pk_transaction PRIMARY KEY (transaction_id) NOT ENFORCED
)
USING DELTA
COMMENT 'Silver conformed transactions: union of sample.dbo.transaction_db, transaction_excel.xlsx and transaction_csv.csv, deduplicated on transaction_id; source of gold.fact_transaction.'
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true'
);

ALTER TABLE migration_demo.banking_mig_silver.transaction ADD CONSTRAINT ck_transaction_transaction_type_len CHECK (transaction_type IS NULL OR length(transaction_type) <= 50);
