"""Port of Talend ``Load_DimBranch``: bronze.sqlserver_branch -> silver.branch -> gold.dim_branch.

Talend job (``talend_jobs/Load_DimBranch.zip``, ``process/Load_DimBranch_0.1.item``)::

    tDBInput_1 (tMSSqlInput, dbo.branch, TRIM_ALL_COLUMN=false)
      -> tMap_1 (to_DimBranch: BranchID = row1.branch_id, BranchName = row1.branch_name,
                 BranchLocation = row1.branch_location; no Var, no lookups, no filter)
      -> tDBOutput_1 (tMSSqlOutput, DWH.DimBranch, TABLE_ACTION=CREATE_IF_NOT_EXISTS,
                      DATA_ACTION=INSERT, DIE_ON_ERROR=false)

The tMap is a pure rename: no trim, no case change, no type conversion. Silver therefore only
types/conforms the bronze snapshot; gold renames to the legacy PascalCase columns and loads with
the shared SCD-1 ``merge_scd1`` (ticket 4) instead of Talend's plain INSERT.
"""
from __future__ import annotations

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import IntegerType, StringType, StructField, StructType, TimestampType

from banking_etl.bronze.sqlserver import bronze_table
from banking_etl.config import GOLD_DIM_BRANCH, SILVER_BRANCH, Settings
from banking_etl.gold.merge import merge_scd1

SILVER_SCHEMA = StructType([
    StructField("branch_id", IntegerType(), True),
    StructField("branch_name", StringType(), True),
    StructField("branch_location", StringType(), True),
    StructField("_ingested_at", TimestampType(), True),
    StructField("_source", StringType(), True),
])

# tMap_1 output table ``to_DimBranch``: target column -> source column (expression ``row1.<col>``).
TMAP_TO_DIM_BRANCH = {
    "BranchID": "branch_id",
    "BranchName": "branch_name",
    "BranchLocation": "branch_location",
}
DIM_KEY_COLS = ["BranchID"]
DIM_UPDATE_COLS = ["BranchName", "BranchLocation"]


def silver_branch_table(settings: Settings) -> str:
    return settings.table("silver", SILVER_BRANCH)


def dim_branch_table(settings: Settings) -> str:
    return settings.table("gold", GOLD_DIM_BRANCH)


def to_silver_branch(bronze_df: DataFrame) -> DataFrame:
    """Type/conform ``bronze.sqlserver_branch`` to ``silver.branch``.

    Values are passed through unchanged (Talend applies no trim or case change); bronze audit
    columns are kept for lineage, NULL if absent.
    """
    cols = []
    for field in SILVER_SCHEMA.fields:
        col = F.col(field.name) if field.name in bronze_df.columns else F.lit(None)
        cols.append(col.cast(field.dataType).alias(field.name))
    return bronze_df.select(cols)


def to_dim_branch(silver_df: DataFrame) -> DataFrame:
    """tMap_1 ``to_DimBranch``: rename silver columns to the legacy DimBranch columns."""
    return silver_df.select([F.col(src).alias(dst) for dst, src in TMAP_TO_DIM_BRANCH.items()])


def load_silver_branch(spark: SparkSession, settings: Settings) -> dict:
    """Rebuild ``silver.branch`` from the current bronze snapshot (overwrite, like bronze)."""
    source, target = bronze_table(settings, "branch"), silver_branch_table(settings)
    df = to_silver_branch(spark.table(source))
    df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target)
    return {"source": source, "target": target, "rows": spark.table(target).count()}


def ensure_dim_branch(spark: SparkSession, settings: Settings) -> str:
    """Talend ``TABLE_ACTION=CREATE_IF_NOT_EXISTS``: create the gold star schema (ticket 4 DDL) if needed."""
    target = dim_branch_table(settings)
    if not spark.catalog.tableExists(target):
        from banking_etl.gold.ddl import apply_star_schema

        apply_star_schema(spark, settings)
    return target


def load_dim_branch(spark: SparkSession, settings: Settings) -> dict:
    """SCD-1 merge of ``silver.branch`` into ``gold.dim_branch`` on ``BranchID``.

    New BranchIDs are inserted (``BranchKey`` generated by Delta), changed names/locations are
    updated in place (``BranchKey`` stable), unchanged rows are untouched and nothing is deleted.
    Returns the merge metrics plus ``source``/``target``/``rows``.
    """
    source, target = silver_branch_table(settings), ensure_dim_branch(spark, settings)
    dim = to_dim_branch(spark.table(source))
    metrics = merge_scd1(spark, dim, target, DIM_KEY_COLS, DIM_UPDATE_COLS)
    return {"source": source, "target": target, "rows": spark.table(target).count(), **metrics}
