# Databricks notebook source
# MAGIC %md
# MAGIC # Bronze Layer: Ingest Transactions from Excel
# MAGIC
# MAGIC **Source:** `transaction_excel.xlsx` (legacy Excel feed)
# MAGIC
# MAGIC **Target:** `bronze.transactions_excel` Delta table
# MAGIC
# MAGIC This notebook reads the raw Excel transaction file and persists it as a Delta table
# MAGIC in the Bronze layer, preserving the original schema and data exactly as-is.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configuration

# COMMAND ----------

VOLUME_PATH = "/Volumes/banking_dwh/raw_data/source_files"
BRONZE_CATALOG = "banking_dwh"
BRONZE_SCHEMA = "bronze"
TABLE_NAME = "transactions_excel"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Read Raw Excel File
# MAGIC
# MAGIC Databricks supports reading Excel files using the `com.crealytics.spark.excel` library.
# MAGIC If this library is not available, the file should be pre-converted to CSV or Parquet
# MAGIC during the upload step (see `setup/upload_source_data.py`).

# COMMAND ----------

from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    StringType,
    DoubleType,
    TimestampType,
)

# Define schema explicitly to match legacy source
excel_schema = StructType(
    [
        StructField("transaction_id", IntegerType(), True),
        StructField("account_id", IntegerType(), True),
        StructField("transaction_date", TimestampType(), True),
        StructField("amount", DoubleType(), True),
        StructField("transaction_type", StringType(), True),
        StructField("branch_id", IntegerType(), True),
    ]
)

# Primary approach: use spark-excel library (com.crealytics:spark-excel)
# Install via cluster library: com.crealytics:spark-excel_2.12:3.5.1_0.20.4
try:
    df_excel = (
        spark.read.format("com.crealytics.spark.excel")
        .option("header", "true")
        .option("dataAddress", "'Sheet1'!A1")
        .schema(excel_schema)
        .load(f"{VOLUME_PATH}/transaction_excel.xlsx")
    )
    print("Excel file read using spark-excel library.")
except Exception as e:
    print(f"spark-excel not available ({e}), falling back to pre-converted CSV.")
    # Fallback: read from pre-converted CSV (generated by setup/upload_source_data.py)
    df_excel = (
        spark.read.format("csv")
        .option("header", "true")
        .schema(excel_schema)
        .load(f"{VOLUME_PATH}/transaction_excel_converted.csv")
    )
    print("Excel data read from pre-converted CSV fallback.")

print(f"Excel records loaded: {df_excel.count()}")
df_excel.printSchema()
df_excel.show(10, truncate=False)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Data Quality Checks

# COMMAND ----------

from pyspark.sql.functions import col, count, when, lit

null_counts = df_excel.select(
    count(when(col("transaction_id").isNull(), True)).alias("null_transaction_id"),
    count(when(col("account_id").isNull(), True)).alias("null_account_id"),
    count(when(col("amount").isNull(), True)).alias("null_amount"),
)
null_counts.show()

total_records = df_excel.count()
print(f"Total records from Excel source: {total_records}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Write to Bronze Delta Table

# COMMAND ----------

from pyspark.sql.functions import current_timestamp

df_bronze = df_excel.withColumn(
    "_ingestion_timestamp", current_timestamp()
).withColumn("_source_file", lit("transaction_excel.xlsx"))

df_bronze.write.format("delta").mode("overwrite").option(
    "overwriteSchema", "true"
).saveAsTable(f"{BRONZE_CATALOG}.{BRONZE_SCHEMA}.{TABLE_NAME}")

print(
    f"Bronze table {BRONZE_CATALOG}.{BRONZE_SCHEMA}.{TABLE_NAME} written successfully."
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Verify Bronze Table

# COMMAND ----------

spark.sql(
    f"SELECT COUNT(*) AS row_count FROM {BRONZE_CATALOG}.{BRONZE_SCHEMA}.{TABLE_NAME}"
).show()
spark.sql(
    f"SELECT * FROM {BRONZE_CATALOG}.{BRONZE_SCHEMA}.{TABLE_NAME} LIMIT 5"
).show(truncate=False)
